"""Pure assembly-resolution rules and structured failures."""

from .core import resolve_from_facts
from .errors import (
    ACTION_DIM_INCOMPATIBLE,
    CAMERA_MAPPING_INVALID,
    CAMERA_SLOT_AMBIGUOUS,
    CAMERA_SLOT_UNRESOLVED,
    CONTROL_MODE_INCOMPATIBLE,
    INVALID_DESCRIPTION,
    MISSING_INPUT,
    NORM_STATS_INSUFFICIENT,
    STATE_DIM_INCOMPATIBLE,
    UNKNOWN_MODEL,
    UNKNOWN_ROBOT,
    ResolutionError,
)

__all__ = [
    "resolve_from_facts", "ResolutionError",
    "MISSING_INPUT", "INVALID_DESCRIPTION", "UNKNOWN_MODEL", "UNKNOWN_ROBOT",
    "STATE_DIM_INCOMPATIBLE", "ACTION_DIM_INCOMPATIBLE",
    "CAMERA_SLOT_AMBIGUOUS", "CAMERA_SLOT_UNRESOLVED",
    "CONTROL_MODE_INCOMPATIBLE", "NORM_STATS_INSUFFICIENT",
    "CAMERA_MAPPING_INVALID",
]
